apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swagger-swaggereditor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: swagger
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/swagger/swaggereditor
    repoURL: https://github.com/nheidloff/ta-gitops.git
    targetRevision: main
    helm:
      releaseName: swaggereditor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
