apiVersion: v1
kind: Namespace
metadata:
  name: swagger
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: swagger-operator-group
  namespace: swagger
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - swagger
---
